### ISSUE TITLE
Error with JavaDocs?

### ISSUE THREAD

**Issue by kennyk65** [scratches/spring-boot-legacy#6]
Error on mvn build, related to JavaDoc tags:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.9.1:jar (attach-javadoc) on project spring-boot-legacy: MavenReportException: Error while creating archive:
[ERROR] Exit code: 1 - /Users/kenkrueger/git/spring-boot-legacy/spring-boot-legacy/src/main/java/org/springframework/boot/legacy/context/web/AnnotationConfigNonEmbeddedWebApplicationContext.java:123: warning: no @param for beanNameGenerator
[ERROR] public void setBeanNameGenerator(BeanNameGenerator beanNameGenerator) {
[ERROR] ^
[ERROR] /Users/kenkrueger/git/spring-boot-legacy/spring-boot-legacy/src/main/java/org/springframework/boot/legacy/context/web/AnnotationConfigNonEmbeddedWebApplicationContext.java:139: warning: no @param for scopeMetadataResolver
[ERROR] public void setScopeMetadataResolver(ScopeMetadataResolver scopeMetadataResolver) {
[ERROR] ^
[ERROR] /Users/kenkrueger/git/spring-boot-legacy/spring-boot-legacy/src/main/java/org/springframework/boot/legacy/context/web/AnnotationConfigNonEmbeddedWebApplicationContext.java:152: warning: nested tag not allowed: <code>
[ERROR] * <code>@Configuration</code>} classes
[ERROR] ^
[ERROR] /Users/kenkrueger/git/spring-boot-legacy/spring-boot-legacy/src/main/java/org/springframework/boot/legacy/context/web/AnnotationConfigNonEmbeddedWebApplicationContext.java:35: warning: nested tag not allowed: <code>
[ERROR] * <code>@Configuration</code>}-annotated classes, but also plain
[ERROR] ^
[ERROR] /Users/kenkrueger/git/spring-boot-legacy/spring-boot-legacy/src/main/java/org/springframework/boot/legacy/context/web/AnnotationConfigNonEmbeddedWebApplicationContext.java:36: warning: nested tag not allowed: <code>
[ERROR] * {@link org.springframework.stereotype.Component <code>@Component</code>} classes and
[ERROR] ^
[ERROR] /Users/kenkrueger/git/spring-boot-legacy/spring-boot-legacy/src/main/java/org/springframework/boot/legacy/context/web/AnnotationConfigNonEmbeddedWebApplicationContext.java:46: error: unknown tag: Author
[ERROR] * @Author Dave Syer
[ERROR] ^
[ERROR] /Users/kenkrueger/git/spring-boot-legacy/spring-boot-legacy/src/main/java/org/springframework/boot/legacy/context/web/AnnotationConfigNonEmbeddedWebApplicationContext.java:78: warning: nested tag not allowed: <code>
[ERROR] * <code>@Configuration</code>} classes
[ERROR] ^
[ERROR] 
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/Users/kenkrueger/git/spring-boot-legacy/spring-boot-legacy/target/apidocs' dir.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

These JavaDoc tags look fine to me, but the maven plugin is complaining.  The error can be bypassed by running  mvn clean install -Dmaven.javadoc.skip=true

...or by removing the offending javadoc tags.

**Comment by dsyer** [comment]
Fixed. Thanks.
